name: Backend CD - Deploy to AKS

on:
  workflow_run:
    workflows: ["Backend CI - Test, Build and Push Images to ACR"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Attach ACR to AKS (if not already attached)
        run: |
          az aks update \
            --name ${{ secrets.AKS_CLUSTER_NAME }} \
            --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} \
            --attach-acr ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Deploy Backend Manifests (ensure resources exist)
        run: |
          cd k8s/
          kubectl apply -f configmaps.yaml
          kubectl apply -f secrets.yaml
          kubectl apply -f product-db.yaml
          kubectl apply -f order-db.yaml
          kubectl apply -f product-service.yaml
          kubectl apply -f order-service.yaml

      - name: Update backend images with new tag
        run: |
          kubectl set image deployment/product-service-deployment product-service=${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.IMAGE_TAG }}
          kubectl rollout status deployment/product-service-deployment

          kubectl set image deployment/order-service-deployment order-service=${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.IMAGE_TAG }}
          kubectl rollout status deployment/order-service-deployment

      - name: Logout from Azure
        run: az logout
        if: always()
